module.exports = {
  TEACHER: "teacher",
  STUDENT: "student",
  ADMIN: "admin",
  ENGLISH: "English",
  ARABIC: "Arabic",
  ENROLLED: "enrolled",
  CREATED: "created",
  MALE: 1,
  FEMALE: 2,
  BOTH: 3,
  USER: "user",
  COURSE: "course",
  FINISHED: "finished",
  VIDEO: "Video",
  ASSIGNMENT: "Assignment",
  TEST: "Test",
  FORUM_QUESTION: "forum_question",
  FORUM_REPLY: "forum_reply",
  FORUM_UPVOTE: "upvote",
  FORUM_DOWNVOTE: "downvote",
  COURSE_BY_ID: "course_by_id",
  COURSE_BY_URL: "course_by_url",
  FORUM_QUESTIONS_SORT_PARAMETERS: ["votes", "createdAt"],
  COURSE_SORT_PARAMETERS: ["date", "createdAt"],
  AUTOGRADE_TYPE: ["MCQ", "TorF"],
  ESSAY_QUESTION: "Essay",
  TEST_SUBMITTED: 0,
  TEST_GRADED: 1,
  TEST_UNGRADED: 2,
  TEST_NOTSUBMITTED: 3,
  NEWS: "news",
  USER_IMAGE_OPTIONS: { width: 320, height: 320 },
  COURSE_IMAGE_OPTIONS: { width: 1280, height: 720 },
};
