module.exports = {
  TEACHER: "teacher",
  STUDENT: "student",
  ADMIN: "admin",
  ENGLISH: "English",
  ARABIC: "Arabic",
  ENROLLED: "enrolled",
  CREATED: "created",
  MALE: 1,
  FEMALE: 2,
  BOTH: 3,
  USER: "user",
  COURSE: "course",
  FINISHED: "finished",
  VIDEO: "Video",
  ASSIGNMENT: "Assignment",
};
