module.exports = {
  TEACHER: "teacher",
  STUDENT: "student",
  ADMIN: "admin",
  ENGLISH: "English",
  ARABIC: "Arabic",
  ENROLLED: "enrolled",
  CREATED: "created",
  MALE: 1,
  FEMALE: 2,
  BOTH: 3,
  USER: "user",
  COURSE: "course",
  FINISHED: "finished",
  VIDEO: "Video",
  ASSIGNMENT: "Assignment",
  FORUM_QUESTION: "forum_question",
  FORUM_REPLY: "forum_reply",
  FORUM_UPVOTE: "upvote",
  FORUM_DOWNVOTE: "downvote",
  COURSE_BY_ID: "course_by_id",
  COURSE_BY_URL: "course_by_url",
  FORUM_QUESTIONS_SORT_PARAMETERS: ["votes", "createdAt"],
  COURSE_SORT_PARAMETERS: ["date", "createdAt"],
};
